module.exports = {
  tutorialSidebar: [
    // { type: "doc", id: "znajomosc-bhp/index", label: "Znajomość zasad BHP" },
    // { type: "doc", id: "zagrozenia-praca/index", label: "Znajomość zagrożeń na stanowisku" },
    // { type: "doc", id: "nadzor-sprzetu/nadzor-sprzetu", label: "Nadzór nad przydzielonym sprzętem" },
    // { type: "doc", id: "system-loto/system-loto", label: "System LOTO" },
    // { type: "doc", id: "zarzadzanie-gospodarka-odpadami/index", label: "Zarządzanie gospodarką odpadami" },
    { type: "doc", id: "obliczanie-dlugosci-rolki", label: "📏 Obliczanie długości rolki" },
    // {
    //   type: "category",
    //   label: "Operacje (Linia-RAD05)",
    //   items: ["linia-rad05/zamawianie", "linia-rad05/odbior-towaru"],
    // },
    {
      type: "category",
      label: "BHP",
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "bhp",
        },
      ],
    },
    {
      type: "category",
      label: "LKJ",
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "lkj",
        },
      ],
    },
  ],
};
